name: Test Runner

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
          java-package: jdk+fx
          cache: maven
      - name: Run Maven Tests
        run: mvn --batch-mode --update-snapshots verify
